<?php

namespace Eoko\ODM\Driver\DynamoDB\Test;

use Aws\Result;
use Eoko\ODM\Driver\DynamoDB\Test\Entity\UserEntity;

class DynamoDBDriverTableDeletionTest extends BaseTestCase
{

    public static function getClassMetadata($classname = UserEntity::class)
    {
        return parent::getClassMetadata($classname); // TODO: Change the autogenerated stub
    }

    public function testDeleteTable()
    {
        $result = $this->getDriver()->deleteTable(self::getClassMetadata());
        $this->assertInstanceOf(Result::class, $result);
    }

    public static function setUpBeforeClass()
    {
        $retry = 0;
        // Ensure that the Table is finished to be created

        self::getDriver()->createTable(self::getClassMetadata());

        while (self::getDriver()->getTableStatus(self::getClassMetadata()) === 'CREATING' && $retry < 5) {
            sleep($retry++ * $retry);
        }
    }

    public static function tearDownAfterClass()
    {
        $retry = 0;
        // Ensure that the Table is really deleted
        while (!self::getDriver()->isTable(self::getClassMetadata()) && $retry < 5) {
            sleep($retry++ * $retry);
        }
    }
}
